### ISSUE TITLE
Spike dependency tables for seedlot ETL Tool batch update

### ISSUE THREAD

**Issue by marcionemec-daitan** [bcgov/nr-spar#1049] opened 2024-04-25 17:59 UTC
Identify and add dependent SEEDLOT tables to be included in the ETL tool mapping settings

**Comment by SLDonnelly** [comment] 2024-05-13 18:31
https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/Dataset+mappings

**Comment by RMCampos** [comment] 2024-05-15 16:34
Duplicate of #1100

**Closed by RMCampos** 2024-05-15 16:34 UTC

**Comment by SLDonnelly** [comment] 2024-05-15 16:42
Where is this documented?

**Comment by marcionemec-daitan** [comment] 2024-05-15 21:16
Hi @SLDonnelly , you can find the complete documentation here (including the Access requirement matrix table for ETL tool credential):

https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/Dataset+mappings
