### ISSUE TITLE
Update screen five to add tested parent tree pct on frontend

### ISSUE THREAD

**Issue by thiagosanchezenc** [bcgov/nr-spar#401] opened 2023-08-10 17:00 UTC
Implement the new design here:
![Image](https://github.com/bcgov/nr-spar/assets/25162561/db30c747-54d6-4161-847c-6d68fe3fb128)

- User should see calculated values under the info section *Genetic worth and percent of tested parent trees*
- Separate the info section into 2, Effective population size and diversity and Genetic worth

**Comment by craigyu** [comment] 2023-08-23 22:50
Closed, duplicate of #402

**Closed** 2023-09-05 17:16 UTC
