### ISSUE TITLE
SPIKE: Screen reader testing for new SPAR screens

### ISSUE THREAD

**Issue by kevinginley** [bcgov/nr-spar#925] opened 2024-03-22 17:48 UTC
As we get closer to a PROD launch, we'll want to test the A class registration flow using a screen reader to ensure the new screens meet that accessibility standard.

**Acceptance Criteria**
- [ ] Review best practices for screen reader design and testing
- [ ] Document findings in our wiki

After the dev work is done, we'll want to (in another ticket):
- [ ] Try using the A class registration flow using a screen reader
- [ ] Document any issues or pain points that come up for future fixes

**Additional context**
Team Alliance found [this guide](https://bootcamp.uxdesign.cc/the-problem-with-automatically-focusing-the-first-input-and-what-to-do-instead-777a9f598e36) while they're working on screen reader testing.
Also, [WCAG reference](https://www.w3.org/WAI/perspective-videos/speech/).

**Comment by SLDonnelly** [comment] 2024-06-24 16:47
@kevinginley what are the best practices for screen reader design and testing?

**Comment by kevinginley** [comment] 2024-06-24 17:40
The first acceptance criterion of the ticket is to figure that fun stuff out. It will likely involve an automated tool doing an initial review followed by manual testing.

**Comment by kevinginley** [comment] 2024-06-29 01:30
Hi @mgaseta, @SLDonnelly,

I've put some documentation together on our wiki [here](https://github.com/bcgov/nr-spar/wiki/Coding-for-accessibility:-Screen-readers)

From what I can tell, I believe? the majority of the work will be applying the ARIA roles and attributes to different fields, labels, and component controls in the A-Class seedlot registration flow. There are some examples in there but you may want to research more about applying ARIA roles and attributes.

I am happy to work closely with you on this whenever you're ready (and I'm back from vacation :-) )

**Comment by mgaseta** [comment] 2024-08-30 13:26
Documentation is done and the issue is in the done column, so, closing it.

**Closed by mgaseta** 2024-08-30 13:26 UTC
